# Generated by Django 4.0.4 on 2022-06-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='post.category'),
        ),
    ]
