# Generated by Django 4.0.4 on 2022-06-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
