# Generated by Django 4.0.4 on 2022-05-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='porftfolio',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_bio',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
