# Generated by Django 4.0.4 on 2022-05-31 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
